### PR TITLE
No build step

### PR DESCRIPTION
**Pull request by ldesplat**
1) Removes the build step from .jsx to .react.js by making webpack understand .jsx and allowing node to transpile on demand with sourcemap support.
2) Lint .jsx files
3) Add test coverage for generated config.js

If you get an error of XMLHttpRequest is not defined then make sure to do a clean npm install. There is a new version of source-map-support which Lab depends on that was released a few hours ago. Lab does not use shrinkwrap dependencies so we get the fix without a new Lab release.

### CODE REVIEW

**Comment by jedireza** [comment]
Thanks! I can't wait to check this out after work. :tada:

**Comment by jedireza** [comment]
These changes are great. Great work getting this done.

I made some changes you can pull into your fork's branch and then we can merge this.

**Comment by ldesplat** [comment]
Nice job fixing the issues. Interesting how you solved them!

I know config.js is generated and that might be why you don't want to add a test, but my OCD can't take that `Coverage: 99.99% (1/12464)` line! :)

**Comment by jedireza** [comment]
Oh how interesting. I have at test for this locally that was identical to the test in your PR. I thought it was a mistake that you added a "duplicate" test... now I see it's being ignored via `.gitignore`.

**Comment by ldesplat** [comment]
Also, instead of -c, you could include -t 100 in the Lab command line. It will fail the travis builds if you are under 100% test coverage.

**Comment by jedireza** [comment]
Ah, ok. Now I see that although the threshold defaults to `100` using the `-t 100` changes the exit status. Thanks :+1:, let's get that in here too then.

**Pull request merged**
