### PR TITLE
Fix access to props on reset page

### PR DESCRIPTION
**Pull request by vkvam**
Small bug noticed when trying to reset password.

### CODE REVIEW

**Comment by jedireza** [comment]
So was this not a bug?

**Comment by vkvam** [comment]
There is, I just have very little experience with React (or frontend in general) and was a bit trigger happy with the pull-request. Tests where failing, and from other examples seen, the existing code should work. I'll go through some react tutorials later on and may update the pull request if I feel confident with the fix.

Feel free to tackle it yourself if you see it as a quickfix.

**Comment by jedireza** [comment]
Oh I see. Thanks for reporting and creating a PR was a great idea. I opened #195 to track this.

**Comment by vkvam** [comment]
Looks to be a react router v4 related bug: https://jaketrent.com/post/access-route-params-react-router-v4/. 

I've updated tests and propTypes.

**Comment by jedireza** [comment]
Thanks!

**Pull request merged**
