### PR TITLE
issue 109 - move shared admin components

### PR DESCRIPTION
**Pull request by GuilhermeJabur**

### CODE REVIEW

**Comment by GuilhermeJabur** [comment]
hey @jedireza , seems CI failed, any tip?

**Comment by GuilhermeJabur** [comment]
seems that "npm install" command failed, but i didn't touch the package.json or any related doc. :x

**Comment by jedireza** [comment]
Yeah I tried re-running it a couple times. I'll also test locally when I get a chance. Code changes look good so far. 👍

**Comment by GuilhermeJabur** [comment]
great @jedireza, thanks!

**Comment by jedireza** [comment]
Ok @GuilhermeJabur I updated a bunch of dependencies and got the build working again. Let's rebase your branch and try again.

If everything goes smoothly (I think) this is all you have to do.

```bash
$ git fetch upstream
$ git rebase upstream/master
$ git push --force
```

**Comment by GuilhermeJabur** [comment]
done :D

**Comment by GuilhermeJabur** [comment]
Your commands were right, i just had to add upstream as your remote repo with:

git remote add upstream https://github.com/jedireza/aqua

So i could fetch it.

**Comment by jedireza** [comment]
Thanks!! 🙏 👍

**Comment by GuilhermeJabur** [comment]
Thank you!! please keep up this awesome work. :+1:

**Pull request merged**
