### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by jedireza**
This PR does a lot of needed updating. I think what's left is:

 - double check all dependencies are up to date with their major versions
 - `react-router@2.x` landed since this PR started, so we need to update that
 - fix and ensure tests are passing (fyi: we're going from `jsdom@3.x` to `jsdom@8.x`)

If you have some extra cycles and are willing to help out, please work off the `update-deps` branch and create PRs with your changes. We'll merge those changes into `update-deps` and keep this PR as the source of truth.

### CODE REVIEW

**Comment by jedireza** [comment]
This PR does a lot of needed updating. I think what's left is:

 - double check all dependencies are up to date with their major versions
 - `react-router@v2.x` landed since this PR started, so we need to update that
 - fix and ensure tests are passing (fyi: we're going from `jsdom@v3.x` to `jsdom@v8.x`)

If you have some extra cycles and are willing to help out, please work off the `update-deps` branch and create PRs with your changes. We'll merge those changes into `update-deps` and keep this PR as the source of truth.

**Comment by pankajpatel** [comment]
`test/client/pages/login/components/App.js` is having `var App = require('../../../../../client/pages/login/components/App.jsx');`

Either App.js is wrongly present or App.jsx has gone missing.

Any idea?

**Comment by pankajpatel** [comment]
`App.jsx` as in `/client/pages/login/components/App.jsx` is missing with following code:
```
var React = require('react/addons');
var ReactRouter = require('react-router');

var Component = React.createClass({
    render: function () {

        return (
            <ReactRouter.RouteHandler />
        );
    }
});

module.exports = Component;
```

shall I create this file again?

**Comment by pankajpatel** [comment]
I have removed the `lab` errors, now working on the individual error due to deps update.
Majority are because of `ReactRouter` `pushState` changed to `push`
And `jsdom` is not accepting the invalid urls

Many Warnings are thrown up like
```
hapi/no-shadow-relaxed - Definition for rule 'hapi/no-shadow-relaxed' was not found
```

**Comment by pankajpatel** [comment]
Updating `hapi/no-shadow-relaxed` to `hapi/no-shadow`

[https://github.com/continuationlabs/eslint-plugin-hapi/issues/6](https://github.com/continuationlabs/eslint-plugin-hapi/issues/6)

**Comment by jedireza** [comment]
@pankajpatel nice! 👍 Please open a PR from your update-deps branch to the aqua/update-deps branch.

**Comment by pankajpatel** [comment]
At current state CI would throw errors as I there are errors because of ReactRouter rendering and jsdom URL validations.

**Comment by jedireza** [comment]
That's ok, the tests aren't passing here either.

**Comment by ADumaine** [comment]
I recently updated my app to many of the latest packages including react 15.2.  I could add some of that back here.  It looks like there are some outstanding commits on the update deps branch. Should I wait for those to be committed since some will have an affect on other changes?

**Comment by jedireza** [comment]
@ADumaine thanks.

> Should I wait for those to be committed since some will have an affect on other changes?

It would be great if someone could help finish this PR as I'm low on time.

**Comment by ADumaine** [comment]
There are 10 commits by @pankajpatel in the update-deps branch.  If those could be merged, I'll pull from that branch and add my updates.  I don't want to get out of sync or redo changes differently.

**Comment by jedireza** [comment]
@ADumaine there are unaddressed comments on that PR which reduces my confidence in those changes.

**Comment by pankajpatel** [comment]
@jedireza I had started working on them but many things require changes in both test code and main source code.

**Comment by jedireza** [comment]
I've began working on this again. See the `v4-refactor` branch if you're interested.

**Pull request closed without merging**
